specialist = [
  {zh:"任何",en:"Any"},
  {zh:"麻醉科",en:"Anaesthesiology"},
  {zh:"解剖病理學",en:"Anatomical Pathology"},
  {zh:"心臟科",en:"Cardiology"},
  {zh:"心胸肺外科",en:"Cardio-thoracic Surgery"},
  {zh:"臨床腫瘤科",en:"Clinical Oncology"},
  {zh:"社會醫學",en:"Community Medicine"},
  {zh:"深切治療科",en:"Critical Care Medicine"},
  {zh:"皮膚及性病科",en:"Dermatology & Venereology"},
  {zh:"急症科",en:"Emergency Medicine"},
  {zh:"內分泌及糖尿科",en:"Endocrinology, Diabetes & Metabolism"},
  {zh:"家庭醫學",en:"Family Medicine"},
  {zh:"法醫病理學",en:"Forensic Pathology"},
  {zh:"腸胃肝臟科",en:"Gastroenterology & Hepatology"},
  {zh:"外科",en:"General Surgery"},
  {zh:"老人科",en:"Geriatric Medicine"},
  {zh:"血液及血液腫瘤科",en:"Haematology & Haematological Oncology"},
  {zh:"免疫學",en:"Immunology"},
  {zh:"免疫及過敏病科",en:"Immunology & Allergy"},
  {zh:"感染及傳染病科",en:"Infectious Disease"},
  {zh:"危重病學",en:"Intensive Care"},
  {zh:"內科",en:"Internal Medicine"},
  {zh:"內科腫瘤科",en:"Medical Oncology"},
  {zh:"腎病科",en:"Nephrology"},
  {zh:"腦神經科",en:"Neurology"},
  {zh:"神經外科",en:"Neurosurgery"},
  {zh:"核子醫學科",en:"Nuclear Medicine"},
  {zh:"婦產科",en:"Obstetrics & Gynaecology"},
  {zh:"職業醫學",en:"Occupational Medicine"},
  {zh:"眼科",en:"Ophthalmology"},
  {zh:"骨科",en:"Orthopaedics & Traumatology"},
  {zh:"耳鼻喉科",en:"Otorhinolaryngology"},
  {zh:"小兒外科",en:"Paediatric Surgery"},
  {zh:"兒科",en:"Paediatrics"},
  {zh:"紓緩醫學科",en:"Palliative Medicine"},
  {zh:"病理學",en:"Pathology"},
  {zh:"整形外科",en:"Plastic Surgery"},
  {zh:"精神科",en:"Psychiatry"},
  {zh:"公共衛生醫學",en:"Public Health Medicine"},
  {zh:"放射科",en:"Radiology"},
  {zh:"復康科",en:"Rehabilitation"},
  {zh:"生殖醫學科",en:"Reproductive Medicine"},
  {zh:"呼吸系統科",en:"Respiratory Medicine"},
  {zh:"風濕病科",en:"Rheumatology"},
  {zh:"泌尿外科",en:"Urology"}
]

pt = [
  {en:"Any", zh:"任何"},
  {en:"Private", zh:"私人執業"},
  {en:"Hospital Authority", zh:"醫院管理局"},
  {en:"University", zh:"大學"},
  {en:"Others", zh:"其他"}
]

d_list=[
  {en:"Any", zh:"任何" },
  {en:"Yau Ma Tei", zh:"油麻地" },
  {en:"Kowloon Tong", zh:"九龍塘" },
  {en:"Kwun Tong", zh:"觀塘" },
  {en:"Ho Man Tin", zh:"何文田" },
  {en:"Central", zh:"中環" },
  {en:"Lai Chi Kok", zh:"荔枝角" },
  {en:"Sheung Shui", zh:"上水" },
  {en:"Tuen Mun", zh:"屯門" },
  {en:"Tai Wai", zh:"大圍" },
  {en:"Sha Tin", zh:"沙田" },
  {en:"Sheung Wan", zh:"上環" },
  {en:"Tai Po", zh:"大埔" },
  {en:"Mid-Levels", zh:"半山" },
  {en:"Chai Wan", zh:"柴灣" },
  {en:"Happy Valley", zh:"跑馬地" },
  {en:"Pok Fu Lam", zh:"薄扶林" },
  {en:"Sham Shui Po", zh:"深水埗" },
  {en:"Causeway Bay", zh:"銅鑼灣" },
  {en:"Tsim Sha Tsui", zh:"尖沙咀" },
  {en:"Kowloon City", zh:"九龍城" },
  {en:"Jordan", zh:"佐敦" },
  {en:"Mong Kok", zh:"旺角" },
  {en:"Tsuen Wan", zh:"荃灣" },
  {en:"Aberdeen", zh:"香港仔" },
  {en:"Admiralty", zh:"金鐘" },
  {en:"Hung Hom", zh:"紅磡" },
  {en:"Wan Chai", zh:"灣仔" },
  {en:"Prince Edward", zh:"太子" },
  {en:"Fanling", zh:"粉嶺" },
  {en:"Kwai Chung", zh:"葵涌" },
  {en:"Yuen Long", zh:"元朗" },
  {en:"Tseung Kwan O", zh:"將軍澳" },
  {en:"Wong Tai Sin", zh:"黃大仙" },
  {en:"To Kwa Wan", zh:"土瓜灣" },
  {en:"Choi Hung", zh:"彩虹" },
  {en:"Cheung Sha Wan", zh:"長沙灣" },
  {en:"San Po Kong", zh:"新蒲崗" },
  {en:"Kowloon Bay", zh:"九龍灣" },
  {en:"Ngau Tau Kok", zh:"牛頭角" },
  {en:"Lam Tin", zh:"藍田" },
  {en:"Ma On Shan", zh:"馬鞍山" },
  {en:"Quarry Bay", zh:"鰂魚涌" },
  {en:"Tai Koo", zh:"太古" },
  {en:"Western", zh:"西區" },
  {en:"Sai Wan Ho", zh:"西灣河" },
  {en:"West Kowloon", zh:"西九龍" },
  {en:"North Point", zh:"北角" },
  {en:"Tsing Yi", zh:"青衣" },
  {en:"Mei Foo", zh:"美孚" },
  {en:"Tsz Wan Shan", zh:"慈雲山" },
  {en:"Tin Shui Wai", zh:"天水圍" },
  {en:"Sai Kung", zh:"西貢" },
  {en:"Tai Kok Tsui", zh:"大角咀" },
  {en:"Siu Sai Wan", zh:"小西灣" },
  {en:"Heng Fa Chuen", zh:"杏花村" },
  {en:"Shau Kei Wan", zh:"筲箕灣" },
  {en:"Shek Kip Mei", zh:"石硤尾" },
  {en:"Repulse Bay", zh:"淺水灣" },
  {en:"Lok Fu", zh:"樂富" },
  {en:"Diamond Hill", zh:"鑽石山" },
  {en:"Discovery Bay", zh:"愉景灣" },
  {en:"Tung Chung", zh:"東涌" },
  {en:"Lantau", zh:"大嶼山" },
  {en:"Chek Lap Kok", zh:"赤臘角" },
  {en:"Fo Tan", zh:"火炭" },
  {en:"Tin Hau", zh:"天后" },
  {en:"Shek O", zh:"石澳" },
  {en:"Fortress Hill", zh:"炮台山" },
  {en:"Stanley", zh:"赤柱" },
]

g=[
  {en:"Any", zh:"任何"},
  {en:"Male", zh:"男性"},
  {en:"Female", zh:"女性"},
]


listMap = {
  SPECIALIST:specialist,
  DISTRICT:d_list,
  PRACTIVE:pt,
  GENDER:g
}

initialState = {
  query:{
    SPECIALIST:0,
    DISTRICT:0,
    PRACTIVE:0,
    GENDER:0,
  }
}
